Copy over quickstart .deployer as a base

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -30,6 +30,10 @@ inputs:
     default: ''
     required: false
     type: string
+  tag:
+    description: Specify a tag to deploy; defaults to PR number
+    required: false
+    type: string
   triggers:
     description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)
     required: false
@@ -59,66 +63,88 @@ inputs:
 outputs:
   triggered:
     description: 'Has a deployment has been triggered?'
-    value: ${{ jobs.deploys.outputs.triggered }}
+    value: ${{ steps.triggers.outputs.triggered }}
 
 runs:
   using: composite
   steps:
-    # Clone, for charts
-    - uses: actions/checkout@v3
+    # Triggers will fire if omitted or matched against a diff
+    - uses: bcgov-nr/action-diff-triggers@v0.2.0
+      id: triggers
+      with:
+        triggers: ${{ inputs.triggers }}
+
+    # Exit if no deployment required/triggered
+    - if: steps.triggers.outputs.triggered == 'false'
+      shell: bash
+      run: |
+        echo "No deployment required/triggered!"
+        exit 0
+
+    # Otherwise, keep going
+    - uses: actions/checkout@v4
       with:
         repository: ${{ inputs.repository }}
         ref: ${{ inputs.branch }}
 
-    # Process variables and inputs
-    - id: vars
-      shell: bash
+    # Get the associated PR number, if one was used or merged
+    - name: Get PR Number
+      id: pr
+      uses: bcgov-nr/action-get-pr@v0.0.1
+
+    # Use any provided tags, otherwise use the PR number
+    - name: Set Tag
+      id: tag
       run: |
-        # Expand for inputs and variables
-
-        # Bug mitigation - OpenShift/Kubernetes hates images with capitals in org/repo names
-        REPO=${{ inputs.repository }}
-        if [[ $REPO != ${REPO,,} ]]; then
-          echo -e "An OpenShift bug prevents capital letters in repo names.\n"
-          echo -e "Please handle that using the `repository` parameter.\n"
-          exit 1
-        fi
-
-        # Triggers
-        TRIGGERS=${{ inputs.triggers }}
-        if [ -z "${TRIGGERS}" ]; then
-          echo "Triggers omitted, deployment required"
-          echo "triggered=true" >> $GITHUB_OUTPUT
-          exit 0
+        if [ -z ${{ inputs.tag }} ]; then
+          echo "tag=${{ steps.pr.outputs.pr }}" >> $GITHUB_ENV
         else
-          echo "Processing triggers"
-          git fetch origin "${{ inputs.diff_branch }}"
-          while read -r check; do
-            for t in "${TRIGGERS[@]}"; do
-              if [[ "${check}" =~ "${t}" ]]; then
-                  echo -e "Triggered: ${t}\n --> ${check}"
-                  echo "triggered=true" >> $GITHUB_OUTPUT
-                  exit 0
-              fi
-            done
-          done < <(git diff origin/"${{ inputs.diff_branch }}" --name-only)
+          echo "tag=${{ inputs.tag }}" >> $GITHUB_ENV
         fi
-        echo "Triggers not matched, deployment skipped"
 
-    - if: steps.vars.outputs.triggered
+    - name: Deploy
+      working-directory: ${{ inputs.directory }}
       shell: bash
       run: |
-        # Login to OpenShift/Kubernetes (NOTE: project command is a safeguard)
-        oc login --token=${{ inputs.token }} --server=${{ inputs.server }}
-        oc project ${{ inputs.namespace }}
+          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
+          oc project ${{ vars.OC_NAMESPACE }} # Safeguard!
 
-    - if: steps.vars.outputs.triggered
-      shell: bash
-      run: |
-        helm ${{ inputs.command }} ${{ inputs.release }} ${{ inputs.directory }} ${{ inputs.parameters }} \
-          | sed '/^kind: Secret/,/^---/{//!d}' | sed '/^kind: Secret/ s/$/ \n  <REDACTED>/'
+          # Interrupt any previous jobs (status = pending-upgrade)
+          PREVIOUS=$(helm status ${{ env.repo_release }} -o json | jq .info.status || true)
+          if [[ ${PREVIOUS} =~ pending ]]; then
+            echo "Rollback triggered"
+            helm rollback ${{ env.repo_release }} || \
+              helm uninstall ${{ env.repo_release }}
+          fi
 
+          # Clean previous deployments for PR pipeline, if any 
+          if [[ '${{inputs.environment}}' == '' ]]; then
+            helm uninstall ${{ env.repo_release }} || true
+            # Remove Bitnami Postgres PVCs
+            oc delete pvc data-${{ env.repo_release }}-bitnami-pg-0 || \
+              echo "Not found: pvc data-${{ env.repo_release }}-bitnami-pg-0"
+          fi
+
+          # Prepare Helm chart
+          helm dependency update
+          helm package --app-version="$tag" --version=$tag .
+          
+          # Deploy Helm chart
+          helm upgrade \
+            --set-string global.repository=${{ github.repository }} \
+            --set-string global.tag=$tag \
+            ${{ inputs.params }} \
+            --install --wait --atomic  ${{ env.repo_release }} \
+            --timeout ${{ inputs.timeout-minutes }}m \
+            --values ${{ inputs.values }} \
+            ./${{ github.event.repository.name }}-$tag.tgz
+
+          # Print history
+          helm history ${{ env.repo_release }}
+          
+          # Remove old build runs, build pods and deployment pods
+          oc delete po --field-selector=status.phase==Succeeded || true
     # Action repo needs to be present for cleanup/tests
     - name: Checkout to make sure action.yml is present (tests)
       if: ${{ github.repository }} != ${{ inputs.repository }}
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
