feat: setup workflows and branch protection (#6)
Co-authored-by: OMPRAKASH MISHRA <omprakashmishra3978@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,17 +1,28 @@
 name: Helm Deployer
-description: Helm wrapper intended for use with github.com/bcgov-nr/quickstart-openshift
+description: Helm wrapper intended for use with github.com/bcgov/quickstart-openshift
 branding:
   icon: package
   color: blue
 
 inputs:
   ### Required
+  oc_namespace:
+    description: 'OpenShift namespace'
+    required: true
+  oc_token:
+    description: 'OpenShift token'
+    required: true
   release:
-    description: Deployment release; usually PR number, test or prod
+    description: Deployment release; usually repo-name-[PR|test|prod]
     required: true
     type: string
 
   ### Typical / recommended
+  directory:
+    description: 'Chart directory'
+    default:  'charts/${{ github.event.repository.name }}'
+    required: false
+    type: string
   environment:
     description: Environment name; omit for PRs
     required: false
@@ -36,11 +47,9 @@ inputs:
     type: string
 
   ### Usually a bad idea / not recommended
-  directory:
-    description: 'Chart directory'
-    default: 'charts'
-    required: false
-    type: string
+  delete_completed:
+    description: Delete completed pods
+    default: true
   timeout-minutes:
     description: 'Timeout minutes'
     default: 10
@@ -52,14 +61,6 @@ inputs:
     required: false
     type: string
 
-secrets:
-  oc_namespace:
-    description: 'OpenShift namespace'
-    required: false
-  oc_token:
-    description: 'OpenShift token'
-    required: false
-
 outputs:
   triggered:
     description: 'Has a deployment has been triggered?'
@@ -68,78 +69,91 @@ outputs:
 runs:
   using: composite
   steps:
-    # Triggers will fire if omitted or matched against a diff
+    ### Triggers, tags and early exits
+
+    # Check triggers (omitted or matched), exiting early if not fired
     - uses: bcgov-nr/action-diff-triggers@v0.2.0
       id: triggers
       with:
         triggers: ${{ inputs.triggers }}
-
-    # Exit if no deployment required/triggered
     - if: steps.triggers.outputs.triggered == 'false'
       shell: bash
       run: |
         echo "No deployment required/triggered!"
         exit 0
 
-    # Otherwise, keep going
-    - uses: actions/checkout@v4
-
-    # Get the associated PR number, if one was used or merged
-    - name: Get PR Number
-      id: pr
-      uses: bcgov-nr/action-get-pr@v0.0.1
-
     # Use any provided tags, otherwise use the PR number
-    - name: Set Tag
-      id: tag
-      run: |
-        if [ -z ${{ inputs.tag }} ]; then
-          echo "tag=${{ steps.pr.outputs.pr }}" >> $GITHUB_ENV
-        else
-          echo "tag=${{ inputs.tag }}" >> $GITHUB_ENV
-        fi
-
-    - name: Deploy
-      env:
-        repo_release: ${{ github.event.repository.name }}-${{ inputs.release }}
-      working-directory: ${{ inputs.directory }}
+    - id: pr
+      uses: bcgov-nr/action-get-pr@v0.0.1
+    - id: vars
       shell: bash
       run: |
-          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
-          oc project ${{ secrets.oc_namespace }} # Safeguard!
+        # Set repo release name, which tacks the repo name onto the release, avoiding collisions
+        echo "repo_release=${{ github.event.repository.name }}-${{ inputs.release }}" >> $GITHUB_OUTPUT
 
-          # Interrupt any previous jobs (status = pending-upgrade)
-          PREVIOUS=$(helm status ${{ env.repo_release }} -o json | jq .info.status || true)
-          if [[ ${PREVIOUS} =~ pending ]]; then
-            echo "Rollback triggered"
-            helm rollback ${{ env.repo_release }} || \
-              helm uninstall ${{ env.repo_release }}
-          fi
+        # Set tag to PR number if inputs.tag not provided
+        if [ -z ${{ inputs.tag }} ]; then
+          echo "tag=${{ steps.pr.outputs.pr }}" >> $GITHUB_OUTPUT
+        else
+          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
+        fi
 
-          # Clean previous deployments for PR pipeline, if any 
-          if [ -z ${{ inputs.environment }} ]; then
-            helm uninstall ${{ env.repo_release }} || true
-            # Remove Bitnami Postgres PVCs
-            oc delete pvc data-${{ env.repo_release }}-bitnami-pg-0 || \
-              echo "Not found: pvc data-${{ env.repo_release }}-bitnami-pg-0"
-          fi
+    ### Deploy
 
-          # Prepare Helm chart
-          helm dependency update
-          helm package --app-version="$tag" --version=$tag .
-          
-          # Deploy Helm chart
-          helm upgrade \
-            --set-string global.repository=${{ github.repository }} \
-            --set-string global.tag=$tag \
-            ${{ inputs.params }} \
-            --install --wait --atomic  ${{ env.repo_release }} \
-            --timeout ${{ inputs.timeout-minutes }}m \
-            --values ${{ inputs.values }} \
-            ./${{ github.event.repository.name }}-$tag.tgz
+    # OC Login
+    - shell: bash
+      run: |
+        # OC Login
+        oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
+        oc project ${{ inputs.oc_namespace }} # Safeguard!
 
-          # Print history
-          helm history ${{ env.repo_release }}
-          
-          # Remove old build runs, build pods and deployment pods
-          oc delete po --field-selector=status.phase==Succeeded || true
+    # Stop pre-existing deployments
+    - shell: bash
+      run: |
+        # Interrupt any previous deployments (status = pending-upgrade)
+        PREVIOUS=$(helm status ${{ steps.vars.outputs.repo_release }} -o json | jq .info.status || true)
+        if [[ ${PREVIOUS} =~ pending ]]; then
+          echo "Rollback triggered"
+          helm rollback ${{ steps.vars.outputs.repo_release }} || \
+            helm uninstall ${{ steps.vars.outputs.repo_release }}
+        fi
+
+    # DEV cleanup, too risky for higher level environments
+    - if: inputs.environment != ''
+      shell: bash
+      run: |
+        # DEV-only cleanup
+
+        # Remove any Helm releases and Bitnami Postgres PVCs 
+        helm uninstall ${{ steps.vars.outputs.repo_release }} || true
+        oc delete pvc data-${{ steps.vars.outputs.repo_release }}-bitnami-pg-0 || true
+
+    # Deploy
+    - uses: actions/checkout@v4
+    - shell: bash
+      working-directory: ${{ inputs.directory }}
+      run: |
+        # Prepare Helm chart
+        helm package -u . --app-version="${{ steps.vars.outputs.tag }}" --version=${{ steps.vars.outputs.tag }}
+
+        # Deploy Helm chart
+        helm upgrade \
+          --set-string global.repository=${{ github.repository }} \
+          --set-string global.tag=${{ steps.vars.outputs.tag }} \
+          ${{ inputs.params }} \
+          --install --wait --atomic ${{ steps.vars.outputs.repo_release }} \
+          --timeout ${{ inputs.timeout-minutes }}m \
+          --values ${{ inputs.values }} \
+          ./${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.tgz
+
+        # Print history
+        helm history ${{ steps.vars.outputs.repo_release }}
+
+    ### Cleanup
+
+    # Completed pod cleanup
+    - if: inputs.delete_completed == 'true'
+      shell: bash
+      run: |
+        # Expand for succeeded pod cleanup (optional)
+        oc delete po --field-selector=status.phase==Succeeded || true
