Drop environment input

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,10 +27,6 @@ inputs:
     default:  'charts/${{ github.event.repository.name }}'
     required: false
     type: string
-  environment:
-    description: Environment name; omit for PRs
-    required: false
-    type: string
   oc_server:
     default: https://api.silver.devops.gov.bc.ca:6443
     description: 'OpenShift server'
@@ -46,7 +42,7 @@ inputs:
     required: false
     type: string
   triggers:
-    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)
+    description: Paths used to trigger a deployment; e.g. ('./backend/' './frontend/)
     required: false
     type: string
 
@@ -72,7 +68,7 @@ runs:
   steps:
     ### Triggers, tags and early exits
 
-    # Check triggers (omitted or matched), exiting early if not fired
+    # Check triggers (omitted or matched), exiting successfully if not fired/required
     - uses: bcgov-nr/action-diff-triggers@v0.2.0
       id: triggers
       with:
@@ -126,15 +122,12 @@ runs:
             helm uninstall ${{ steps.vars.outputs.repo_release }}
         fi
 
-    # DEV cleanup, too risky for higher level environments
-    - if: inputs.cleanup == 'true'
-      shell: bash
-      run: |
-        # Pre-deploy cleanup
-
-        # Remove any Helm releases and Bitnami Postgres PVCs 
-        helm uninstall ${{ steps.vars.outputs.repo_release }} || true
-        oc delete pvc data-${{ steps.vars.outputs.repo_release }}-bitnami-pg-0 || true
+    # # Development=true interrupts existing  up jobs, but causes downtime
+    # - if: inputs.development == 'true'
+    #   shell: bash
+    #   run: |
+    #     # Pre-deploy cleanup
+    #     oc delete pvc data-${{ steps.vars.outputs.repo_release }}-bitnami-pg-0 || true
 
     # Package Helm chart
     - uses: actions/checkout@v4
@@ -167,8 +160,7 @@ runs:
     ### Cleanup
 
     # Completed pod cleanup
-    - if: inputs.cleanup == 'true'
-      shell: bash
+    - shell: bash
       run: |
         # Expand for succeeded pod cleanup (optional)
         oc delete po --field-selector=status.phase==Succeeded || true
